### ISSUE TITLE
How to handle multiple messages to single agent scenrio

### ISSUE THREAD

**Issue by Kothakapu** [tompaana/bot-message-routing#10]
Hi @tompaana , This package is superb and great work.

Can we handle multiple messages to same agent at a time and agent can answers to them one by one(Scenario which I required is something how we chant Skype for business).

Thanks in Advance.

Thanks,
Satheesh K.

**Comment by tompaana** [comment]
Hi,

Thanks, I'm glad you find this project interesting!

The scenario you describe sounds like something in here: https://github.com/tompaana/intermediator-bot-sample/issues/27

So in short: Yes, this component should be able to handle that. In the "worst" case, you may need to reconsider the connection datatype (`Dictionary` is somewhat limiting) and changing the implementation of some methods. All the methods that may need changing are `virtual` so you could override them in your bot project without the need to change the code in this project.

Br,
Tomi
