### ISSUE TITLE
SendMessageAsync should allow use of custom bot credentials

### ISSUE THREAD

**Issue by JohnGalt1717** [tompaana/bot-message-routing#12]
Hi there, we're using custom bot id keys etc. (don't know if that matters). When await _messageRouterManager.SendMessageToPartyByBotAsync(
                    conversationClientParty, messageToConversationClient); is called it returns fine but it doesn't respond in the channel. (using web chat) I hooked up to the response of it and that is always null when it returns.

How do I get this to respond back to the channel with a please wait?

Also similarly I'm not getting notified on the watching endpoint that there is a request waiting. I'm assuming this is all related?

**Comment by tompaana** [comment]
Thanks for reporting the issue!

It is reasonable to think the issues you mentioned are related. What do you mean by "custom bot id keys"? Could you please try to provide more info? I'm afraid there's not enough here for me to solve the case. Note that one requirement in order for the routing to work is that there must be a bot instance in the same channel/platform as the person/bot you want to message.

**Comment by JohnGalt1717** [comment]
So by default the bot framework uses MicrosoftBotId and MicrosoftBotPassword in the web.config (or environment). We have multiple bots so we have different key pairs for each one. We're using the C# IntermediatorBotSample code as a starting point to make this work. So we've set everything up and just overridden the  new ConnectorClient line to explicitly pass the right keys.  This made the ReplyToActivityAsync not through an Unauthorized error but it doesn't respond back.

Otherwise it's identical to the sample.  Our responding human is on Microsoft Teams and has issued command watch and gets a positive response saying it's monitoring.  The requesting human is on web or the emulator and doesn't get a notice that they're in queue waiting for someone to respond even though the response code sends and doesn't throw an error.

Does that help?

**Comment by tompaana** [comment]
Thanks for the info. Unfortunately, I can't still tell you what's wrong right off the bat. I can, however, provide some tips on how to investigate the issue:
* Test Intermediator Bot sample as-is, if you haven't already
* Debug the result handler - break point here: https://github.com/tompaana/intermediator-bot-sample/blob/master/IntermediatorBotSample/MessageRouting/MessageRouterResultHandler.cs#L173
* Use Azure Storage Explorer (or some other tool) to see what's happening in the table storage

**Comment by JohnGalt1717** [comment]
So the sample works... until you change the name of the keys in the web.config file and in the botsettings file. Then it fails in exactly the same way.

Conversely I was able to get it to all work if I made the same keys in our web.config file.  Obviously this doesn't work when there are 2 bots hosted on the same app.

Looks like something in the SendMessageToPartyByBotAsync is making assumptions as to the keys that are being used and not asking for them and since there is no way to pass the keys or the values there is no way to override this.  At least though it's easy to reproduce. Just change the key names in the botSettings and web.config to something else (and update the ApiController BotAuthentication attribute accordingly) and it will fail.

Also it's not clear what BotId is. I've set it to the name of our bot which seems to work, but I'd love to know what that is supposed to be as well and wherever it needs to look it up an override needs to be there to pass it in instead of making the assumption.

Thanks!

**Comment by tompaana** [comment]
I think I understand now. `SendMessageToPartyByBotAsync` used `MessagingUtils` class (of this project) to send the messages and it creates an instance of `ConnectorClient`. Thus, your keys are ignored. See https://github.com/tompaana/bot-message-routing/blob/master/BotMessageRouting/Utils/MessagingUtils.cs#L102 and https://github.com/tompaana/bot-message-routing/blob/master/BotMessageRouting/Utils/MessagingUtils.cs#L83

For now you could override the functionality in your code to fix the issue.

**Comment by JohnGalt1717** [comment]
Thanks.  It looks like I would have to pull in all of RoutingDataManager and the utils function for this to be overridden for now correct?

Any idea when this might be fixed?

**Comment by JohnGalt1717** [comment]
Note also that MessageRouterManager.HandleActivityAsync also has the problem.

**Comment by tompaana** [comment]
I intentionally made many of the methods `virtual` so that you could derive your own classes to override the functionality. Unfortunately, I cannot give a specific date when this enhancement will be available. If you create a nice solution, I won't turn down your PR :)

**Comment by JohnGalt1717** [comment]
Well, the way I was thinking this should work was an overridden constructor that allows you to pass the Keys or the values for them when creating the router. Does that make sense?

Were you thinking for something else?

**Comment by JohnGalt1717** [comment]
The other problem is the sample implies that it can work with custom credentials but can't. So that would need to be updated. Not sure how you'd want that to be laid out given the change directly affects the settings functionality.  The way I'm doing it is that I've converted everything to taking the keys in the constructor and then pass those on each of my API calls and create everything there instead of in the WebApiConfig file but I don't know if that makes sense or not.

**Comment by tompaana** [comment]
You could make your derived class take the keys in the constructor. That's perfectly fine. I need more time to think how I'm going to handle this ticket overall, but I simply have no time at the moment. I suggest that in the meanwhile you do whatever works for you.

**Comment by JohnGalt1717** [comment]
Ok. I was going to pitch in with a PR, just didn't want to take it in the wrong direction on you.

**Comment by tompaana** [comment]
I truly appreciate your help! If you want, throw me a proposal and if needed I can refactor it later. Thanks!

**Comment by tompaana** [comment]
The `development_v4` branch now contains a `MessageRouter` class with all virtual public methods. In other words, you can now derive a custom version of the class.

**Comment by JohnGalt1717** [comment]
Ok, so is there a tutorial coming on this? Specifically what I'm looking for, and I suspect just about anyone looking at this would want to see, is this:

1. User logs into website
2. User interacts with bot and bot knows that it's them because token or something is passed through the bot framework.
3. Bot can't help the user so offers to escalate to a human.
4. Bot looks up against a list of available users to answer
5. Bot then connects both parties and listens in while they talk allowing for recording of entire conversation.
6. Bot handles disconnects/reconnects, "missed user" scenarios allowing roll down to next available human, etc.

I'd argue that all of this should just be built directly into the bot framework but in the mean time a sample or at least a tutorial blog would be very helpful.

**Comment by tompaana** [comment]
@JohnGalt1717 I'll see how well and which bits of the items in your list I can incorporate to the [Intermediator Bot Sample](https://github.com/tompaana/intermediator-bot-sample/tree/development)... The things is, it's pretty much just me working on the C# sample right now and my capacity is limited.

**Comment by JohnGalt1717** [comment]
@tompaana  Thank you!

Here's hoping you get more resources, because if this stuff doesn't get done the Bot Framework is going to die on the vine once people realize how seriously limited it is and that it won't do the most common use case required by business out of the box. (to say nothing of the fact that you can't make a bot link to Cortana with a corporate azure subscription, nor create an Cortana skill in the same case which basically means Cortana also gets to die on the vine while this isn't fixed.)

I'd strongly suggest you bring this up at a staff meeting and raise hell to get these core issues fixed before Microsoft becomes completely irrelevant in the bot space and makes the position of Cortana even worse than it is as business bail because it's not possible to actually write to it as a business care of limitations of public Microsoft Accounts instead of being able to Office 365 accounts and your managed subscriptions etc.

At this point we've written our own bot system in SignalR because we gave up on Microsoft Bot Framework because of these issues. We'd love to come back and use the framework but until these core issues are addressed we can't. And I know for a fact that 3 fortune 500 companies are in the same boat, except they're starting to use a competitor's tech instead of Microsoft's.

**Comment by tompaana** [comment]
@JohnGalt1717 Thank you, sir. You make a fine point. I will focus my efforts next week on working on the solution + acquiring additional resources.
