### ISSUE TITLE
Get Agent watch status

### ISSUE THREAD

**Issue by 20112077** [tompaana/bot-message-routing#13]
Add a function to check if a watching Agent is available for the handover

**Comment by tompaana** [comment]
Good issue(!), but wrong project; the message routing component shouldn't care about this or about agents for that matter. The purpose of this project is to simply a) keep track of users/bots and b) provide means to route messages.

Please report the issue in https://github.com/tompaana/intermediator-bot-sample

Thanks,
Tomi
