### ISSUE TITLE
Enable N:N connections

### ISSUE THREAD

**Issue by chetan279** [tompaana/bot-message-routing#15]
I can't connect to multiple customer at a time.
Can I do this for multiple users?

 messageRouterResult = await messageRouterManager.ConnectAsync(
                        senderParty,
                        partyToAcceptOrReject,
                        createNewDirectConversation);

**Comment by tompaana** [comment]
We can make this happen - might be difficult to manage the situation though: Every message an agent writes would be forwarded to all the customers. I guess there's a case where this would a desired effect.

**Comment by tompaana** [comment]
Technical change: Connections should be defined using duples instead of current data type (`Dictionary<Party, Party>).

**Comment by tompaana** [comment]
The `development_v4` branch now allows N:N connections.
