### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Cdlhj** [tompaana/bot-message-routing#16]
Hi, I am looking for a simple sample for BOT to Human Handoff (e.g. Agent via Skype). If I try to open following links I get just this Error: Error establishing a database connection
http://tomipaananen.azurewebsites.net/?p=1851
http://tomipaananen.azurewebsites.net/?p=2231
May be you can fix it?
Kind regards Jan

**Comment by tompaana** [comment]
@Cdlhj Thanks for bringing this to my attention! I'm investigating the issue, and it starts to look like the database is just not there anymore! I managed to rescue the content from cache. I may want to change the blog platform altogether, but in the meanwhile will add the articles here.

**Comment by Cdlhj** [comment]
Hi Tomi,

I appreciate your quick answer very much and I am looking forward to your articles.  Despite my age of 69 I am very new to the whole BOT story and I haven’t work with C# for at least 6 years, so you can imagine how “easy” is to start for me J

Kind regards from Switzerland

Jan Linhart

 

Von: Tomi Paananen [mailto:notifications@github.com] 
Gesendet: Montag, 16. April 2018 13:07
An: tompaana/bot-message-routing
Cc: Cdlhj; Mention
Betreff: Re: [tompaana/bot-message-routing] Links not working (#16)

 

@Cdlhj <https://github.com/Cdlhj>  Thanks for bringing this to my attention! I'm investigating the issue, and it starts to look like the database is just not there anymore! I managed to rescue the content from cache. I may want to change the blog platform altogether, but in the meanwhile will add the articles here.

**Comment by tompaana** [comment]
Migration has begun: https://tompaana.github.io/
