### ISSUE TITLE
"Agent" using Facebook Messenger fails to send messages to "client"

### ISSUE THREAD

**Issue by petemason** [tompaana/bot-message-routing#8]
First off, this package is absolutely wonderful. Great job! It works great if I use the emulator or sms but I've found a scenario where there seems to be a bug. 

If I use Facebook messenger to issue the "command watch", I get the expected, "This channel/conversation is now where the requests are aggregated". Then if I use my cell phone, via sms, to request a "human" the process works great, asking to accept the conversation request. Then, after accepting, if I send messages from my cell phone (sms) those messages arrive just fine in Messenger but if I try to respond to the "client" from Messenger I receive:

"You said: hello
Type "command options" to see all command options.
Type "human" to initiate conversation with human agent."

Indicating the conversation is not connected.

![routingbug](https://user-images.githubusercontent.com/4306123/34073458-0a884d30-e260-11e7-8d12-13044ba9f631.jpg)

**Comment by tompaana** [comment]
Possibly fixed in commit 74f2312e9711a3b15b63a79563376dafd06af58e

Also: This could be an issue in Intermediator Bot Sample instead. I will start working on that next now that v1.0 of this component is out.

**Comment by tompaana** [comment]
Tested to work with version: https://github.com/tompaana/intermediator-bot-sample/commit/49c7f08c10da4c6004ff4dad735ba18cc86972cd
